# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "main.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\nmain.proto\x12\x04main\"5\n\x08\x41Request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x01\"\xc1\x03\n\tAResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x19\n\x01\x61\x18\x02 \x01(\x0b\x32\x0e.main.ARequest\x12\x12\n\x01\x62\x18\x03 \x01(\x0e\x32\x07.main.B\x12\t\n\x01\x63\x18\x04 \x03(\t\x12\x13\n\x08\x64_string\x18\x89' \x01(\tH\x00\x12\x1c\n\x11\x64_string_optional\x18\x8a' \x01(\tH\x00\x12\x19\n\x01\x65\x18\x06 \x03(\x0b\x32\x0e.main.ARequest\x12!\n\x01\x66\x18\x07 \x03(\x0b\x32\x16.main.AResponse.FEntry\x12!\n\x01g\x18\x08 \x03(\x0b\x32\x16.main.AResponse.GEntry\x12\x17\n\x03h_B\x18\xa9\x46 \x01(\x0e\x32\x07.main.BH\x01\x12%\n\nh_ARequest\x18\xaa\x46 \x01(\x0b\x32\x0e.main.ARequestH\x01\x12\x12\n\x07h_int32\x18\xab\x46 \x01(\x05H\x01\x12\x13\n\x08h_string\x18\xac\x46 \x01(\tH\x01\x1a(\n\x06\x46\x45ntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x38\n\x06GEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.main.ARequest:\x02\x38\x01\x42\x03\n\x01\x64\x42\x03\n\x01h*1\n\x01\x42\x12\x14\n\x10\x45NUM_UNSPECIFIED\x10\x00\x12\n\n\x06TYPE_1\x10\x01\x12\n\n\x06TYPE_2\x10\x02\x32-\n\x01\x41\x12(\n\x05hello\x12\x0e.main.ARequest\x1a\x0f.main.AResponseb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "main_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ARESPONSE_FENTRY"]._loaded_options = None
    _globals["_ARESPONSE_FENTRY"]._serialized_options = b"8\001"
    _globals["_ARESPONSE_GENTRY"]._loaded_options = None
    _globals["_ARESPONSE_GENTRY"]._serialized_options = b"8\001"
    _globals["_B"]._serialized_start = 527
    _globals["_B"]._serialized_end = 576
    _globals["_AREQUEST"]._serialized_start = 20
    _globals["_AREQUEST"]._serialized_end = 73
    _globals["_ARESPONSE"]._serialized_start = 76
    _globals["_ARESPONSE"]._serialized_end = 525
    _globals["_ARESPONSE_FENTRY"]._serialized_start = 417
    _globals["_ARESPONSE_FENTRY"]._serialized_end = 457
    _globals["_ARESPONSE_GENTRY"]._serialized_start = 459
    _globals["_ARESPONSE_GENTRY"]._serialized_end = 515
    _globals["_A"]._serialized_start = 578
    _globals["_A"]._serialized_end = 623
# @@protoc_insertion_point(module_scope)
