# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: main.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'main.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x04main\"\x18\n\x08\x41Request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tAResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x0e\n\x0cHelloServiceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AREQUEST']._serialized_start=20
  _globals['_AREQUEST']._serialized_end=44
  _globals['_ARESPONSE']._serialized_start=46
  _globals['_ARESPONSE']._serialized_end=74
  _globals['_HELLOSERVICE']._serialized_start=76
  _globals['_HELLOSERVICE']._serialized_end=90
# @@protoc_insertion_point(module_scope)
